### ISSUE TITLE
Request to add option to toggle Inline type definitions on and off

### ISSUE THREAD

**Issue by tomweston** [mengzhuo/yaml-to-go#3]
[json-to-go](https://mholt.github.io/json-to-go/) Added the ability to toggle on and off inline type definitions in the generated go structs. 

The addition of this toggle would be greatly appreciated!

**Comment by Zhwt** [comment]
> 
> 
> [json-to-go](https://mholt.github.io/json-to-go/) Added the ability to toggle on and off inline type definitions in the generated go structs.
> 
> The addition of this toggle would be greatly appreciated!

I made a fork added this toggle, and also fixed some other issue, you can try this:
[https://zhwt.github.io/yaml-to-go/](https://zhwt.github.io/yaml-to-go/)

**Comment by mengzhuo** [comment]
@Zhwt 
I'm happy to transfer this project to you and maintain it.

**Comment by Zhwt** [comment]
@mengzhuo That sounds great! Just one more question, since I forked the repository a few months ago, and committed some changes, how can I merge those commits together? I'm a little bit new here and didn't have any experience about project transfer or something like that, it would be nice if you can give me some help or advice! : )

**Comment by mengzhuo** [comment]
It should be fine since I didn't change anything.
You can either send pull request or accept the ownership transfer.

**Comment by mengzhuo** [comment]
Github can't transfer personal repos while your repos is existed.
"Zhwt/yaml-to-go already exists"

**Comment by mengzhuo** [comment]
@Zhwt
Hi, I've add you as collaborator, happy hacking.
